### ISSUE TITLE
我最在行辅助答题运行出错

### ISSUE THREAD

**Issue by ygmyth** [game-helper/weixin#37]
在 macOS 10.13 ，ubuntu 16.04 下运行 npm run robot 均出现以下错误，nodejs 版本满足要求，依赖完整，在windows下 没有问题

```

src/match/index.js:11
module.exports = async player => {
                       ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myth/Develop/opensource/demo/wo/src/robot.js:1:77)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ robot: `node src/robot.js`
npm ERR! Exit status 1
```

**Comment by zhuweiyou** [comment]
看报错是语法错误，`node -v` 输出什么呢

**Comment by ygmyth** [comment]
v6.11.2

**Comment by zhuweiyou** [comment]
README 上说了，9.x
