### ISSUE TITLE
小白提问：npm run ca报错

### ISSUE THREAD

**Issue by bitternolis** [game-helper/weixin#52]
F:\weixin-master\包你懂我>npm run ca

> @ ca F:\weixin-master\包你懂我
> anyproxy-ca

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\weixin-master\包你懂我\node_modules\anyproxy\bin\anyproxy-ca:15:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ca: `anyproxy-ca`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ca script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\nodejs\node_cache\_logs\2018-05-04T19_01_50_158Z-debug.log

**Comment by CheneyHen** [comment]
之前使用过这个，没啥问题，环境是win10x64。RUN CA这个只是生成代理服务器的证书，供代理服务器解析https用。你这个貌似生成CA证书的代码出毛病了。

**Comment by CheneyHen** [comment]
现在确实报错了。没法产生CA证书，并扔了一个错误，和你的提示差不多

**Comment by zhuweiyou** [comment]
从报错看，是缺少了包。

npm i 安装的时候有没有报错？试着删了 node_modules 目录，再重新 npm i 发下看看。

**Comment by bitternolis** [comment]
试过了，同样的，rebuild也没用

**Comment by bitternolis** [comment]
安装时报了几个warning
F:\weixin-master\大家来找茬腾讯版>npm i
npm WARN 大家来找茬腾讯版 No repository field.
npm WARN 大家来找茬腾讯版 No license field.

up to date in 4.224s

**Comment by zhuweiyou** [comment]
这个 warning 倒不是问题。

![image](https://user-images.githubusercontent.com/8413791/39670144-e15e584c-5130-11e8-9c23-4515037801c8.png)
![image](https://user-images.githubusercontent.com/8413791/39670151-06a247c6-5131-11e8-9434-fd0158bd3200.png)


刚试了新机器（win10 x64）和我本机 macOS 都没问题的。

另外看到有人给 anyproxy 提了这个 BUG  https://github.com/alibaba/anyproxy/issues/364 你可以尝试一下 
```bash
npm install inquirer -g
```

**Comment by bitternolis** [comment]
确实成功了
